name: weather_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0-332.0.dev

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  json_annotation: ^4.9.0
  retrofit: ^4.4.1
  dio: ^5.7.0
  talker: ^4.5.2
  talker_dio_logger: ^4.5.2
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  dartz: ^0.10.1
  easy_debounce: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  retrofit_generator: ^9.1.5
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true